### ISSUE TITLE
Add a new organization to ROR: 
 
Mental Asylum of Education

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#584] opened 2022-03-30 08:28 UTC
Summary of request: Add a new organization to ROR

Update record:
Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Merge/split/deprecate records:
Organizations affected by this change:
ROR ID(s) of organization(s) affected by this change: 
How should the record(s) be changed? 

Add record:
Name of organization: Mental Asylum of Education
Website: arjundahal.blogspot.com
Link to publications: https://orcid.org/0000-0001-7796-7971
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: https://isni.org/isni/0000000502642565
GRID ID: 
Crossref Funder ID: 
Aliases: मेन्टल असाइलम अफ एजुकेशन 
Labels:
Acronym/abbreviation: MAOE, maoe
Related organizations: 
City: Gauradaha-3, Jhapa
Country: Nepal
Geonames ID:
Year established: 2021
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request:

**Comment by adambuttrick** [comment] 2022-04-01 04:23
Dupe of declined request #187.

**Closed by adambuttrick** 2022-04-01 04:23 UTC
Labels: duplicate
