### ISSUE TITLE
Add a new organization to ROR: National Institute for the Defense of Competition and the Protection of Intellectual Property

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#253] opened 2021-08-13 22:47 UTC
Summary of request: Add a new organization to ROR

Name of organization: Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual
Website: https://www.indecopi.gob.pe/inicio
Link to publications: https://repositorio.indecopi.gob.pe
Type: Government
Wikipedia page: https://es.wikipedia.org/wiki/Instituto_Nacional_de_Defensa_de_la_Competencia_y_de_la_Protecci%C3%B3n_de_la_Propiedad_Intelectual
Wikidata ID: https://www.wikidata.org/wiki/Q5917502
ISNI ID: https://isni.org/isni/000000098931233
GRID ID:
Crossref Funder ID:
Ringgold ID:
Other names for the organization: National Institute for the Defense of Competition and the Protection of Intellectual Property
Acronym/abbreviation: INDECOPI
Related organizations:
Date established: 1952
City: Lima
Country: Peru
Other information about this request:

**Comment by mariagould** [comment] 2021-08-13 22:47
Flagged item from bulk list. Comments from Arthur: I'm not sure on this one - it's not clear it's really a research-related organization, it seems to be more a regulatory agency. However it does do something related to patents, so maybe? See this publication: https://repositorio.indecopi.gob.pe/handle/11724/4399

**Comment by adambuttrick** [comment] 2022-03-17 19:30
Duplicate of request in #233.

**Closed by adambuttrick** 2022-03-17 19:30 UTC
Labels: level 1, new record, lion
