### ISSUE TITLE
Add a new organization to ROR: Universidad Internacional de Investigacion Mexico

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#16232] opened 2024-12-09 00:08 UTC
Summary of request: Add a new organization to ROR

Name of organization: Universidad Internacional de Investigacion Mexico*es
Website: https://uiimex.edu.mx
Domains: uiimex.edu.mx 
Link to publications: 
Organization type: Education
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Aliases: 
Labels: Mexico International Research University*en
Acronym/abbreviation: UIIMEX*es
Related organizations: 
City: Benito Juárez
Country: Mexico
Geonames ID: 
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by rileymmarsh** [comment] 2024-12-19 15:51
Duplicate of #16222

**Closed by rileymmarsh** 2024-12-19 15:51 UTC
Labels: level 1, new record, jaguar, triage needed
