### ISSUE TITLE
Add a new organization to ROR: 
 
Beacon Science & Consulting

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#555] opened 2022-03-21 23:39 UTC
Summary of request: Add a new organization to ROR

Add record:
Name of organization: Beacon Science & Consulting
Website: https://beaconscience.com.au/
Link to publications: https://eos.org/opinions/microplastics-hidden-contribution-to-snow-melting
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases:
Labels: 灯塔科学咨询事务所*Chinese;
Acronym/abbreviation: BS&C
Related organizations: 
City: Adelaide
Country: Australia
Geonames ID: 2078025
Year established: 2019
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To be integrated in a scholarly publishing system

**Comment by adambuttrick** [comment] 2022-03-22 01:49
Duplicate of declined request #295.

**Closed** 2022-03-22 01:49 UTC
Labels: out of scope
