### ISSUE TITLE
Add a new organization to ROR: 
 
NBIS, National Bioinformatics Infrastructure Sweden

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#591] opened 2022-04-01 08:36 UTC
Summary of request: Add a new organization to ROR

Update record:
Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Merge/split/deprecate records:
Organizations affected by this change:
ROR ID(s) of organization(s) affected by this change: 
How should the record(s) be changed? 

Add record:
Name of organization: NBIS, National Bioinformatics Infrastructure Sweden
Website: https://nbis.se
Link to publications: already submitted
Organization type: Government (An organization that is part of or operated by a national or regional government and that conducts or supports research)
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: NBIS
Labels:
Acronym/abbreviation: NBIS
Related organizations: 
City: Uppsala
Country: Sweden
Geonames ID:
Year established: 2008
How will a ROR ID for this organization be used? To identify affiliations for research publications, To acknowledge research funders, To acknowledge a research facility

Other information about this request:

**Comment by adambuttrick** [comment] 2022-04-02 01:58
Duplicate of #519

**Closed by adambuttrick** 2022-04-02 01:58 UTC
Labels: duplicate
