### ISSUE TITLE
Add a new organization to ROR: Korean Drug. CO., LTD.

### ISSUE THREAD

**Issue by bearlss** [ror-community/ror-updates#2035] opened 2023-01-17 04:52 UTC
Summary of request: Add a new organization to ROR

Name of organization: Korean Drug. CO., LTD.
Website: https://www.nicepharma.com/
Link to publications: https://www.hindawi.com/
Organization type: Company (A private for-profit corporate entity involved in conducting or sponsoring research)
Wikipedia page:
Wikidata ID:
ISNI ID:
GRID ID:
Crossref Funder ID:
Other names for the organization: 고려제약 (주)
Acronym/abbreviation: KDC
Related organizations: 
City: Seoul
Country: Korea
Geonames ID: 
Year established:1982
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To be integrated in a scholarly publishing system
Other information about this request: for submission of Hindawi

**Comment by adambuttrick** [comment] 2023-01-17 17:13
Duplicate of #2034

**Closed by adambuttrick** 2023-01-17 17:13 UTC
Labels: duplicate, new record
