### ISSUE TITLE
Modify the information in an existing ROR record: 
Bundesamt für Seeschifffahrt und Hydrographie https://ror.org/03ycvrj88


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#464] opened 2022-02-03 13:47 UTC
Summary of request: Modify the information in an existing ROR record

Name of organization: Bundesamt für Seeschifffahrt und Hydrographie
ROR ID: https://ror.org/03ycvrj88
Which part of the record needs to be changed? Organization website
Description of change: Please change URL of website in:    https://www.bsh.de/ 

Name of organization: 
Website: 
Link to publications: 
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: 
Labels:
Acronym/abbreviation: 
Related organizations: 
City: 
Country: 
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request:

**Comment by adambuttrick** [comment] 2022-02-03 13:58
Duplicate of #461.

**Closed** 2022-02-03 13:59 UTC
Labels: duplicate, level 2, update record, kitten
