### ISSUE TITLE
Modify the information in an existing ROR record: 
State Flight Academy of Ukraine (old name) https://ror.org/03cfeg204


### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#445] opened 2022-01-27 09:50 UTC
Summary of request: Modify the information in an existing ROR record

Name of organization: State Flight Academy of Ukraine (old name)
ROR ID: https://ror.org/03cfeg204
Which part of the record needs to be changed? Primary name, Other names or name versions listed in the record, Organization website
Description of change: Primary name: Flight Academy National Aviation University, Flight Academy NAU (link - http://www.klanau.kr.ua/images/docs/Pologennya_LANAU.pdf, page 5; https://www.wikidata.org/wiki/Q3010496); 

other names: Льотна академія Національного авіаційного універсиетету, Льотна академія НАУ  (link - http://www.klanau.kr.ua/images/docs/Pologennya_LANAU.pdf, page 5, https://nau.edu.ua/ua/menu/navchalni-pidrozdili/academy/kirovogradska-lotna-akademiya.html);

website: http://sfa.org.ua, http://www.glau.kr.ua

Name of organization: 
Website: 
Link to publications: 
Organization type: 
Wikipedia page: 
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Other names for the organization: 
Acronym/abbreviation: 
Related organizations: 
City: 
Country: 
Year established: 
How will a ROR ID for this organization be used? 
Other information about this request: I recently wrote a letter about this to your colleague "Isidro F. Aguillo" on 2021.09.21

**Comment by adambuttrick** [comment] 2022-01-27 22:01
The first website provided doesn't resolve, so can't approve that part of the request. Current URL in the ROR record (https://ror.org/03cfeg204) resolves correctly, but features the version of the name requestor wants changed. 

Wikipedia entry and Wikidata do use this form, as well as the first link. The second link is for "Льотна академія Національного авіаційного університету," which is in the request as an alternate form, as well as in the Wikipedia entry. 

I think this might be OK from reference to secondary, government references. See https://universities.studyinukraine.gov.ua/en/minedu/university/134/agents and https://ssu.gov.ua/en/video-galleries/sbu-opryliudnyla-dokazy-khabarnytstva-i-vruchyla-novu-pidozru-nachalnyku-lotnoi-akademii

**Comment by adambuttrick** [comment] 2022-02-10 22:34
Duplicate of #308.

**Closed by adambuttrick** 2022-02-10 22:34 UTC
Labels: level 1, update record, jaguar
