### ISSUE TITLE
Add a new organization to ROR: 

### ISSUE THREAD

**Issue by mcs6977088** [ror-community/ror-updates#6044] opened 2023-10-27 05:38 UTC
Summary of request: Add a new organization to ROR

Name of organization:Hunan Communication Polytechnic
Website: http://www.hnjtzy.com.cn
Link to publications: 
Organization type: Education
Wikipedia page:
Wikidata ID: Q15914728
ISNI ID: 0000 0004 1759 698X
GRID ID:
Crossref Funder ID:
Other names for the organization: Hu Nan Jiao Tong Zhi Ye Ji Shu Xue Yuan
Acronym/abbreviation:
Aliases:
Labels: 湖南交通职业技术学院*Chinese
Related organizations: 
City: Changsha, Hunan Province
Country:China
Geonames ID: 1815577
Year established:1956
How will a ROR ID for this organization be used?  For institutional accreditation when submitting a thesis
Other information about this request:

**Comment by adambuttrick** [comment] 2023-10-27 06:10
Polytechnic institute and vocational school in China. Funds and employs researchers. Solid affiliation usage. Should be added.

**Comment by adambuttrick** [comment] 2023-11-06 23:57
Potentially a duplicate of https://ror.org/01gng0007. Asking region expert for review.

**Comment by adambuttrick** [comment] 2023-11-08 22:35
Assigned ROR ID https://ror.org/03y4gzw57 in release v1.36.

**Closed by adambuttrick** 2023-11-08 22:35 UTC
Labels: level 1, new record, jaguar
