### ISSUE TITLE
Add a new organization to ROR: Kumaraguru college of Technology

### ISSUE THREAD

**Issue by saranyaKise** [ror-community/ror-updates#1522] opened 2022-11-07 08:47 UTC
Summary of request: Add a new organization to ROR

Name of organization: Kumaraguru College of Technology
Website: www.kct.ac.in
Link to publications: https://doi.org/10.32604/csse.2022.021164
Organization type: Education
Wikipedia page: -
Wikidata ID: -
ISNI ID: -
GRID ID: -
Crossref Funder ID: -
Other names for the organization: 
Acronym/abbreviation:KCT 
Related organizations: 
City: Coimbatore
Country:India
Geonames ID: 
Year established:1984
How will a ROR ID for this organization be used? 
Other information about this request:
In reputed publication.

**Comment by adambuttrick** [comment] 2022-11-07 17:06
Duplicate of #1521

**Closed by adambuttrick** 2022-11-07 17:06 UTC
Labels: new record
