### ISSUE TITLE
Add a new organization to ROR: 
 
Associação Brasileira de Editores Científicos

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-updates#509] opened 2022-02-25 17:21 UTC
Summary of request: Add a new organization to ROR

Update record:
Name of organization: 
ROR ID: 
Which part of the record needs to be changed? 
Description of change: 

Merge/split/deprecate records:
Organizations affected by this change:
ROR ID(s) of organization(s) affected by this change: 
How should the record(s) be changed? 

Add record:
Name of organization: Associação Brasileira de Editores Científicos
Website: https://www.abecbrasil.org.br/
Link to publications: https://doi.org/10.21452/procpc_07 (on affiliation); https://www.abecbrasil.org.br/arquivos/ABEC_Meeting_Live_2020_Resenhas_Criticas.pdf (on Acknowledgement)
Organization type: Other (Use this category for any organization that does not fit the categories above)
Wikipedia page: http://wiki.abecbrasil.org.br/mediawiki-1.26.2/index.php?title=P%C3%A1gina_principal
Wikidata ID: 
ISNI ID: 
GRID ID: 
Crossref Funder ID: 
Aliases: Brazilian Association of Scientific Editors
Labels:
Acronym/abbreviation: ABEC; ABEC Brasil; ABEC BRASIL; Abec Brasil
Related organizations: 
City: Botucatu
Country: Brazil
Year established: 1985
How will a ROR ID for this organization be used? To identify affiliations for research publications, To identify affiliations for datasets, To acknowledge research funders, To acknowledge a research facility, To be integrated in a scholarly publishing system

Other information about this request: ABEC Brasil is a non profit organization founded on November 28, 1985.
It brings together individuals and companies interested in developing and improving the publication of technical-scientific journals; communication and dissemination of information. Support the exchange of ideas, the debate of problems and the defense of common interests.

**Comment by adambuttrick** [comment] 2022-02-25 17:27
Duplicate of #388.

**Closed by adambuttrick** 2022-02-25 17:27 UTC
Labels: duplicate, level 2, update record, kitten
