### ISSUE TITLE
Modify the information in an existing ROR record: Lietuvos Mokslo Taryba - https://ror.org/02gs16m83

### ISSUE THREAD

**Issue by adambuttrick** [ror-community/ror-updates#15979] opened 2024-11-25 17:54 UTC
Summary of request: Modify the information in an existing ROR record

Name of organization: Lietuvos Mokslo Taryba
ROR ID: https://ror.org/02gs16m83
Which part of the record needs to be changed? Site, domains

Update: website.replace==https://lmt.lrv.lt | domains.add==lmt.lrv.lt$

**Comment by Gabrielius-lmt** [comment] 2024-11-27 20:19
Hello, sorry, but accidentally I registered the same request: **Modify the information in an existing ROR record: Lietuvos mokslo taryba https://ror.org/02gs16m83 #16028.** So I just want to inform you and waiting changing for request.

**Comment by adambuttrick** [comment] 2024-11-27 20:45
@Gabrielius-lmt Thanks for flagging this. I've closed as https://github.com/ror-community/ror-updates/issues/16028 as a duplicate of this request. We will publish the link update in our next release.

**Comment by Gabrielius-lmt** [comment] 2024-11-27 20:48
Thank you !
And we waiting for changing request.

Pagarbiai
Gabrielius Suslovas
Informacinių technologijų skyriaus vedėjas

Tel. +370 676 16215
El. p. ***@***.******@***.***>
Gedimino pr. 3, 01103 Vilnius
[Image]<https://lmt.lrv.lt/lt/naujienu-prenumerata/>

From: Adam ***@***.***>
Date: Wednesday, 27 November 2024 at 22:46
To: ror-community/ror-updates ***@***.***>
Cc: Gabrielius Suslovas | Lietuvos mokslo taryba ***@***.***>, Mention ***@***.***>
Subject: Re: [ror-community/ror-updates] Modify the information in an existing ROR record: Lietuvos Mokslo Taryba - https://ror.org/02gs16m83 (Issue #15979)

@Gabrielius-lmt<https://github.com/Gabrielius-lmt> Thanks for flagging this. I've closed as #16028<https://github.com/ror-community/ror-updates/issues/16028> as a duplicate of this request. We will publish the link update in our next release.

**Closed** 2024-12-11 05:41 UTC
Labels: level 2, update record, jaguar
